### ISSUE TITLE
IME support on macOS

### ISSUE THREAD

**Issue by Wengier** [nanshiki/SDL-IM-plus#1]
The IME support on Windows and Linux platforms is apparently very useful. Many thanks for your work. I wonder if it is possible to add macOS support as well? macOS has built-in input sources similar to the Windows platform, so macOS users can set them up pretty easily when compared with the Linux platform.

**Comment by Wengier** [comment]
FYI I have made the following commit in the DOSBox-X repo which appears to allow IME to work on SDL2-based macOS builds:

https://github.com/joncampbell123/dosbox-x/commit/425bf580b84a16f4dbf6fc14099862d089861bf9

There are differences between SDL1 and SDL2 libraries regarding IME support, but I hope it helps demonstrate how it may work on a modified SDL1 library including SDL-IM-Plus.

**Comment by nanshiki** [comment]
I only have a very old Mac mini and I am not familiar with macOS programming so it would be difficult to respond.
And I think I saw something about SDL1 not being compatible with recent macOS. 
I have no plans to support SDL2.

**Comment by Wengier** [comment]
I am aware that this repo is for SDL1, but I linked to a commit that allows IME to work in macOS with SDL2 in order to show how such support may be possibly done even for SDL1 (say porting some code or so). I have recently bought a macBook M2 laptop (with latest macOS version) which soon becomes my main computer (due to its faster speed), and SDL1 library works fine with it too, although unfortunately no IME support yet of course (unlike modified SDL2). I am not that familiar with the interfaces as used by SDL-IM-plus so it is not so easy for me to implement them properly.

**Comment by nanshiki** [comment]
@Wengier I managed to cope with macOS.
The correspondence in DOSBox-X was done first. DOSBox-X supports IME even with SDL2.
